```{r}
library(ggplot2)
library(dplyr)
library(openxlsx)
```

```{r}
colnames(T_BIAŁYSTOK) <- c("Rok", "I", "II", "III", "IV","V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" )

```


```{r}
histogram_theme <- theme(
  text = element_text(size=15),
  axis.title = element_text(family ="sans", size = 20 ),
  plot.background = element_rect(fill = "#FAF8FF"),
  panel.background = element_rect(fill="white"),
  panel.grid = element_line(linewidth = 0.9, color="gray93"),
  panel.grid.major.y = element_line(linewidth = 1),
  panel.grid.major.x = element_line(linewidth = 0.4, linetype = "dashed"),
  panel.grid.minor.y = element_line(linewidth = 0.4),
  panel.grid.minor.x = element_blank(),
  legend.position = "none"
)

#Używamy pętli for, aby nie musieć pisać kodu dla każdego miesiąca
for (i in colnames(T_BIAŁYSTOK)[2:13])
{
  #otwarcie nowego okna dla każdego wykresu
  #dev.new()
  
  #chcemy wygenerować gradient dla każdego wykresu, potrzebujemy do tego przedziału temperatur, aby dopasować do niego przedział kolorów
  min1= (min(T_BIAŁYSTOK[,i])-min(T_BIAŁYSTOK[2:13]))/(max(T_BIAŁYSTOK[2:13]) - min(T_BIAŁYSTOK[2:13]))
  max1= (max(T_BIAŁYSTOK[,i])-min(T_BIAŁYSTOK[2:13]))/(max(T_BIAŁYSTOK[2:13]) - min(T_BIAŁYSTOK[2:13]))
  
  
  print(ggplot(T_BIAŁYSTOK, aes(T_BIAŁYSTOK[,i]))+
          geom_histogram(aes(fill=factor(T_BIAŁYSTOK[,i]), color = factor(T_BIAŁYSTOK[,i])),bins = 8) +
          #dodajemy gradient
          scale_fill_discrete(h=c(400*max1,230+180*min1), c=67 , l=64) +
          scale_color_discrete(h=c(400*max1,230+180*min1), c=67 , l=64)+
          labs(title = i, x="Temperatura", y="Liczba wystąpień") +
          #dodajemy notację dla temperatury
          scale_x_continuous(labels = ~ paste0(.x, " °C"))+
          histogram_theme
        )
}

```


```{r}

liniowy_theme <- theme(
  text = element_text(size=15),
  plot.background = element_rect(fill = "#FAF8FF"),
  panel.background = element_rect(fill="white"),
  panel.grid = element_line(linewidth = 0.9, color="gray93"),
  panel.grid.major.y = element_line(linewidth = 1, linetype = "dashed"),
  panel.grid.minor.y = element_line(linewidth = 0.4, linetype = "dashed"),
  panel.grid.major.x = element_blank(),
  panel.grid.minor.x = element_blank(),
  panel.border = element_rect(linewidth  = 2, fill = NA),
  axis.title = element_text(size = 25, family = "sans"),
  plot.title = element_text(size=30, hjust = 0),
  legend.position  = "none"
  )

#ponownie używamy pętli for
for (i in colnames(T_BIAŁYSTOK)[2:13])
{
  #dev.new()
  print(ggplot(T_BIAŁYSTOK, aes(Rok,T_BIAŁYSTOK[,i],color = T_BIAŁYSTOK[,i]))+ 
          #dodanie wykresu liniowego 
          geom_line(linewidth=0.9) + 
          #dodajemy punkty do wykresu liniowego, aby lepiej zobrazować poszczególne dane (oraz ze względów estetycznych)
          geom_point(aes(fill = T_BIAŁYSTOK[,i]), size=5, pch=21) +
          #dodanie gradientu
          scale_fill_gradient2(low="deepskyblue",mid = ,high="#E27C93",midpoint = 7,limits=c(min(T_BIAŁYSTOK[2:13]),max(T_BIAŁYSTOK[2:13]))) +
          scale_color_gradient2(low="deepskyblue",mid ="#D5D5D5",high="#E27C93",midpoint = 7,limits=c(min(T_BIAŁYSTOK[2:13]),max(T_BIAŁYSTOK[2:13])))+ 
          #dodanie notacji dla temperatury
          scale_y_continuous(labels = ~ paste0(.x, " °C"))+
          #tytuły osi
          labs(title=i,x="Rok", y="Temperatura")+ 
          #dodanie przygotowanego wcześniej theme'a
          liniowy_theme)+
      #dodanie geom_smooth
      geom_smooth(method = "lm")
}
```


```{r}
# STATYSTYKI OPISOWE
tabela_miesiace <- data.frame(rownames=c("Średnia", "Mediana", "Odchylenie Standardowe", "Minimum", "Maximum", "Rozstęp miedzykwartylowy"))

for (i in colnames(T_BIAŁYSTOK[,2:13]))
{
  srednia <- mean(T_BIAŁYSTOK[,i])
  mediana <- median(T_BIAŁYSTOK[,i])
  sd <- sd(T_BIAŁYSTOK[,i])
  min <- min(T_BIAŁYSTOK[,i])
  max <- max(T_BIAŁYSTOK[,i])
  iqr <- IQR(T_BIAŁYSTOK[,i])
  temp_tabela <- data.frame(rownames=c(srednia, mediana,sd, min, max, iqr))
  tabela_miesiace<-cbind.data.frame(tabela_miesiace, temp_tabela)
}
colnames(tabela_miesiace)=c(" ", "I", "II", "III", "IV","V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" )
write.xlsx(tabela_miesiace, 'Tabela_miesiace.xlsx') #TU DAJE OD RAZU DO WORKING DIRECTORY


```

```{r}
boxplot(T_BIAŁYSTOK[,2:13])
grid(nx=0,ny=6,lty = "solid",col = "gray93")
boxplot(T_BIAŁYSTOK[,2:13], 
        #border=colorRampPalette(c("deepskyblue", "#E27C93", "#E27C93","deepskyblue"))( 12), 
        col= colorRampPalette(c("deepskyblue", "#E27C93", "#E27C93","deepskyblue"))( 12), 
        #col = "gray93",
        border = "black",
        add=TRUE,
        main="Rozkład temperatur", xlab="miesiące", ylab="tmp[st.C]"
        )
```

```{r}
#PORY ROKU
wiosna <- data.frame(T_BIAŁYSTOK[,1], round(rowMeans(T_BIAŁYSTOK[,4:6]),3))
lato <- data.frame(T_BIAŁYSTOK[,1], round(rowMeans(T_BIAŁYSTOK[,7:9]),3))
jesien <- data.frame(T_BIAŁYSTOK[,1], round(rowMeans(T_BIAŁYSTOK[,10:12]),3))
zima <- data.frame(T_BIAŁYSTOK[,1], round(rowMeans(T_BIAŁYSTOK[,c(13,2,3)]),3))
wegetacja <-  data.frame(T_BIAŁYSTOK[,1], round(rowMeans(T_BIAŁYSTOK[,5:11]),3))

#lista
dane <- list(wiosna,lato,jesien,zima,wegetacja)
names(dane) <- c("wiosna","lato","jesien","zima","wegetacja")

#zmiana nazw
for (i in 1:5){
  colnames(dane[[i]])<-c(names(dane)[i], "Temp")
}

#histogram
histogram <-function(data){
  min1= (min(data[,2])-min(T_BIAŁYSTOK[2:13]))/(max(T_BIAŁYSTOK[2:13]) - min(T_BIAŁYSTOK[2:13]))
  max1= (max(data[,2])-min(T_BIAŁYSTOK[2:13]))/(max(T_BIAŁYSTOK[2:13]) - min(T_BIAŁYSTOK[2:13]))
  
  ggplot(data, aes(data[,2]))+
  geom_histogram(aes(fill=factor(data[,2]), color = factor(data[,2])),bins = 8) +
          scale_fill_discrete(h=c(400*max1,230+180*min1), c=67 , l=64) +
          scale_color_discrete(h=c(400*max1,230+180*min1), c=67 , l=64)+
          labs(title =colnames(data)[1] , x="Temperatura", y="Liczba wystąpień") +
          scale_x_continuous(labels = ~ paste0(.x, " °C"))+
          histogram_theme
}
lapply(dane, histogram)

#wykres liniowy
liniowy <- function(data){
          print(ggplot(data, aes(data[,1],data[,2], color = data[,2]))+
          geom_line(linewidth=0.9) + 
          labs(title=colnames(data)[1],x="Rok", y="Temperatura")+ 
          geom_point(aes(fill = data[,2]), size=5, pch=21) +
          scale_fill_gradient2(low="deepskyblue" ,high="#E27C93",midpoint = 7,limits=c(min(T_BIAŁYSTOK[2:13]),max(T_BIAŁYSTOK[2:13]))) + 
          scale_color_gradient2(low="deepskyblue",mid ="#C5C5C5" ,high="#E27C93",midpoint = 7,limits=c(min(T_BIAŁYSTOK[2:13]),max(T_BIAŁYSTOK[2:13])))+
          scale_y_continuous(labels = ~ paste0(.x, " °C"))+
          liniowy_theme)
}

lapply(dane, liniowy)

#złożenie średnich w jeden df
pory_roku <- data.frame(wiosna)
for (pora in dane[2:5]) {
  pory_roku <- cbind(pory_roku, pora[,2])
}
colnames(pory_roku) <- c("Rok","wiosna","lato","jesień","zima","wegetacja")

#boxplot
boxplot(pory_roku[2:6])
grid(nx=0,ny=5,lty = "solid",col = "gray93")
boxplot(pory_roku[2:6], 
        #border=colorRampPalette(c("deepskyblue", "#E27C93", "#E27C93","deepskyblue"))( 12), 
        col= c("#B888A6", "#E27C93","#B888A6","deepskyblue","#D87886"), 
        #col = "gray93",
        border = "black",
        add=TRUE,
        main="Rozkład temperatur", xlab="miesiące", ylab="temperatura [st.C]")

```


```{r}
tabela_pory_roku <- data.frame(rownames=c("Średnia", "Mediana", "Odchylenie Standardowe", "Minimum", "Maximum", "Rozstęp miedzykwartylowy"))
for (i in colnames(pory_roku[,2:6]))
{
  srednia <- mean(pory_roku[,i])
  mediana <- median(pory_roku[,i])
  sd <- sd(pory_roku[,i])
  min <- min(pory_roku[,i])
  max <- max(pory_roku[,i])
  iqr <- IQR(pory_roku[,i])
  temp_tabela <- data.frame(rownames=c(srednia, mediana,sd, min, max, iqr))
  tabela_pory_roku<-cbind.data.frame(tabela_pory_roku, temp_tabela)
}
colnames(tabela_pory_roku)=c(" ", "wiosna","lato","jesien","zima","wegetacja")
write.xlsx(tabela_pory_roku, 'Tabela_pory_roku.xlsx') #TU DAJE OD RAZU DO WORKING DIRECTORY
```

```{r}
#ŚEDNIE DEKADOWE

#tabela z miesiacami, porami roku, wegetacja
zbiorcza <- merge(T_BIAŁYSTOK, pory_roku, by="Rok" )
#osobne tabele dla dekad
for (i in c(0:6))
{
  nr_dekady<-50+i*10
  assign(paste0("dekada_",1950+i*10), subset(zbiorcza, Rok>1950+i*10 & Rok <=1960+i*10))
  
}
```

```{r}
#tabela ze średnimi dekadowymi dla miesiecy, por roku i wegetacji (tabela_srednie_dekadowe)
dekady <- list(dekada_1950,dekada_1960, dekada_1970, dekada_1980, dekada_1990, dekada_2000, dekada_2010)
names(dekady)<-c("1950","1960", "1970", "1980", "1990", "2000", "2010")

tabela_srednie_dekadowe <- data.frame()
for (i in 1:length(dekady))
{
  liczona_dekada <- dekady[[i]]
  liczona_dekada_nazwa <- names(dekady)[i]
  temp_tabela_srednie <- data.frame(nrows=1)
  for (j in colnames(liczona_dekada[,2:18]))
  {
    srednia_dekady <- mean(liczona_dekada[,j])
    temp_tabela_srednie <- cbind(temp_tabela_srednie, srednia_dekady)
  }
  tabela_srednie_dekadowe <- rbind(tabela_srednie_dekadowe, temp_tabela_srednie)  
}
colnames(tabela_srednie_dekadowe) <- c("Dekada", colnames(zbiorcza[,2:18]))
tabela_srednie_dekadowe[,1]<-names(dekady)
```

```{r}
#wykresy średnich dekadowych
theme_scatter<-liniowy_theme + theme(
  text = element_text(size=12),
  panel.grid.major.y = element_line(linetype = "solid"),
  panel.grid.major.x = element_line(linetype = "solid"),
  panel.grid.minor.y = element_blank(),
)


for (i in colnames(tabela_srednie_dekadowe[,2:18]))
{
  print(ggplot(tabela_srednie_dekadowe, aes(as.numeric(Dekada), tabela_srednie_dekadowe[,i]))+
          geom_smooth(method = "lm", aes(color = ..y..), fill="gray68", alpha = 0.2)+
          geom_point(aes(fill = tabela_srednie_dekadowe[,i]), size=6, pch=21) +
          scale_fill_gradient2(low="deepskyblue" ,high="#E27C93",midpoint = 7,limits=c(min(T_BIAŁYSTOK[2:13]),max(T_BIAŁYSTOK[2:13])))+
          scale_color_gradient2(low="deepskyblue" ,mid ="#C5C5C5" ,high="#E27C93",midpoint = 7,limits=c(min(T_BIAŁYSTOK[2:13]),max(T_BIAŁYSTOK[2:13])))+
          labs(y="Temperatura",x="Dekada" ,title=i)+
          scale_x_continuous(labels = ~ paste0('dekada ',.x), breaks = round(seq(min(tabela_srednie_dekadowe$Dekada),max(tabela_srednie_dekadowe$Dekada),by=10),1))+
          theme_scatter)
}
```
